version: '2'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    volumes:
        - .:/app
    env_file:
        - ./.env.dev
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 app:app --reload --timeout 1000 --log-level DEBUG