version: '3.4'

services:
  covid:
    image: covid
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 app:app --timeout 150 --log-level INFO